### ISSUE TITLE
Can't install adminlte-reactjs

### ISSUE THREAD

**Issue by MeloGit** [booleanhunter/ReactJS-AdminLTE#36]
Hi

When I try to execute npm install for installing adminlte-reactjs. I have errors.

`E:\react_apps\acta1  (adminlte-reactjs@1.0.6)
λ npm install
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:827:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:319:11)
npm WARN addRemoteGit     at emitOne (events.js:77:13)
npm WARN addRemoteGit     at Socket.emit (events.js:169:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:477:12)
npm WARN addRemoteGit  git://github.com/adobe-webplatform/eve.git#eef80ed resetting remote C:\Users\armel.tsanga\AppData\Roaming\npm-cache\_g
it-remotes\git-github-com-adobe-webplatform-eve-git-eef80ed-3ede0067 because of error: { [Error: Command failed: git -c core.longpaths=true c
onfig --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\armel.tsanga\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/adobe-webplat
form/eve.git C:\Users\armel.tsanga\AppData\Roaming\npm-cache\_git-remotes\git-github-com-adobe-webplatform-eve-git-eef80ed-3ede0067: Cloning
into bare repository 'C:\Users\armel.tsanga\AppData\Roaming\npm-cache\_git-remotes\git-github-com-adobe-webplatform-eve-git-eef80ed-3ede0067'
...
npm ERR! git clone --template=C:\Users\armel.tsanga\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/adobe-webplat
form/eve.git C:\Users\armel.tsanga\AppData\Roaming\npm-cache\_git-remotes\git-github-com-adobe-webplatform-eve-git-eef80ed-3ede0067: fatal: u
nable to connect to github.com:
npm ERR! git clone --template=C:\Users\armel.tsanga\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/adobe-webplat
form/eve.git C:\Users\armel.tsanga\AppData\Roaming\npm-cache\_git-remotes\git-github-com-adobe-webplatform-eve-git-eef80ed-3ede0067: github.c
om[0: 192.30.253.113]: errno=No error
npm ERR! git clone --template=C:\Users\armel.tsanga\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/adobe-webplat
form/eve.git C:\Users\armel.tsanga\AppData\Roaming\npm-cache\_git-remotes\git-github-com-adobe-webplatform-eve-git-eef80ed-3ede0067: github.c
om[1: 192.30.253.112]: errno=No error
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"w
in32","arch":"x64"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\armel.tsanga\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall"
npm ERR! node v4.4.5
npm ERR! npm  v4.1.2
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\armel.tsanga\AppData\Roaming\npm-cache\_git-remotes\_templates
--mirror git://github.com/adobe-webplatform/eve.git C:\Users\armel.tsanga\AppData\Roaming\npm-cache\_git-remotes\git-github-com-adobe-webplat
form-eve-git-eef80ed-3ede0067
npm ERR! Cloning into bare repository 'C:\Users\armel.tsanga\AppData\Roaming\npm-cache\_git-remotes\git-github-com-adobe-webplatform-eve-git-
eef80ed-3ede0067'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.113]: errno=No error
npm ERR! github.com[1: 192.30.253.112]: errno=No error
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\react_apps\acta1\npm-debug.log`

**Comment by aayanqazi** [comment]
Try to use it 
`npm update -g minimatch@3.0.2`

**Comment by aayanqazi** [comment]
Or 
`npm update minimatch`
