### ISSUE TITLE
webpack doesn't work

### ISSUE THREAD

**Issue by odelreym** [booleanhunter/ReactJS-AdminLTE#57]
Hi booleanhunter

I have a problem trying to compile with webpack the stuff
```/usr/local/lib/node_modules/webpack-cli/bin/cli.js:244
				throw err;
				^

Error: webpack.optimize.CommonsChunkPlugin has been removed, please use config.optimization.splitChunks instead.
    at Object.get [as CommonsChunkPlugin] (/ReactJS-AdminLTE/node_modules/webpack/lib/webpack.js:165:10)
    at Object.<anonymous> (/ReactJS-AdminLTE/webpack.config.js:48:30)
    at Module._compile (/usr/local/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)


Do you know how to resolve it?

Thanks in advance

Nacho.

**Comment by saraffadarsha** [comment]
@odelreym 
I have converted ES6 version and works with react-scripts and create-react-app
https://github.com/saraffadarsha/ReactJS-AdminLTE
